"use client";
import "./globals.css";
import { ThemeProvider } from "@emotion/react";
import { useColorStore } from "./store/useColorStore";
import "@emotion/react";
import { QueryClientProvider } from "@tanstack/react-query";
import { queryClient } from "./queries/query";
declare module "@emotion/react" {
  export interface Theme {
    backgroundColor: string;
    color: string;
  }
}
// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const currentColor = useStore(useColorStore, (state) => state.color);
  const currentColor = useColorStore((state) => state.color);
  const themes = {
    light: {
      //backgroundColor: "white",
      color: currentColor,
    },
    dark: {
      backgroundColor: "black",
      color: currentColor,
    },
  };
  const theme = themes["light"];
  return (
    <QueryClientProvider client={queryClient}>
      <ThemeProvider theme={theme}>
        <html lang="en">
          <body>{children}</body>
        </html>
      </ThemeProvider>
    </QueryClientProvider>
  );
}
