'use client'
import "./globals.css";
import { ThemeProvider } from '@emotion/react'
import useStore from "./useStore";
import { useColorStore } from "./store/useColorStore";

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentColor = useStore(useColorStore, (state) => state.color);

  const themes = {
    light: {
      // themeColor: 'hotpink'
      backgroundColor: 'white',
      color: currentColor
    },
    dark: {
      // themeColor: 'hotpink'
      backgroundColor: 'black',
      color: currentColor
    }
  }
  const theme = themes['dark']
  return (
    <ThemeProvider theme={theme}>
      <html lang="en">
        <body>{children}</body>
      </html>
    </ThemeProvider>
  )
}
